
name: Build Runtime Image

on:
  push:
    branches:
      - release/stable-with-patches

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi


      - name: Prepare Runtime Build Context
        run: poetry run python openhands/runtime/utils/runtime_build.py --build_folder ./containers/runtime
        env:
          # Ensure the script uses the correct base image if needed, although default should be fine
          # OH_RUNTIME_BASE_IMAGE: nikolaik/python-nodejs:python3.12-nodejs22
          # Ensure the script knows the target repo (though build.sh overrides org later)
          OH_RUNTIME_RUNTIME_IMAGE_REPO: ghcr.io/remind101/runtime # This might not be strictly necessary as build.sh constructs the final path


      - name: Free up disk space by removing tool cache
        run: sudo rm -rf /opt/hostedtoolcache

      - name: Build and Push Runtime Image
        run: |
          echo "Building runtime image with tag stable-with-patches and source tag..."
          # Set DOCKER_IMAGE_TAG for build.sh to pick up
          export DOCKER_IMAGE_TAG=stable-with-patches
          # Override the image name defined in config.sh
          export DOCKER_IMAGE=openhands-runtime
          # Set RELEVANT_SHA for build.sh to add git sha tag (optional but good practice)
          export RELEVANT_SHA=${{ github.sha }}
          ./containers/build.sh -i runtime --push -o remind101
        env:
          # Pass GITHUB_TOKEN for potential git operations within build script if needed
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
